fail_fast: false
default_language_version:
  python: python3
default_stages:
- pre-commit
- pre-push
minimum_pre_commit_version: 3.0.0
repos:
- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks:
  - id: black
    additional_dependencies: [toml]
- repo: https://github.com/timothycrosley/isort
  rev: 5.13.2
  hooks:
  - id: isort
    additional_dependencies: [toml]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.13.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-ast
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace
